### ISSUE TITLE
ESP freezes as soon as I submit the Itho config

### ISSUE THREAD

**Issue by RienduPre** [jodur/ESPEASY_Plugin_ITHO#5]
Hi,

Tried it no many time with different modules, but as soon as I submit the Itho config in the ESP_EASY web interface the ESP freezes and a reboot does not help. (See screenshot)

I have to reset the ESP and reflash the binary to get into a fresh config again.
<img width="1064" alt="2018-06-25_1549" src="https://user-images.githubusercontent.com/9009949/41854236-fd208e16-788f-11e8-8981-e1ba54da574d.png">

**Comment by matthijsf** [comment]
I have the exact same issue. Were you able to find a workaround.

**Comment by RienduPre** [comment]
No -:)

**Comment by matthijsf** [comment]
What type of esp are you having issues on. I’m running a bare esp12-e. Will try on an wemos later.

**Comment by matthijsf** [comment]
I'm not sure what esp the bin is built for. However, I've tried to manually build it for a normal_ESP8266_1024 and the build fails with the following errors.

`C:/Users/matthijs/Desktop/ESP/ESPEasy-mega/src/_P145_Itho.ino:` In function 'boolean Plugin_145(byte, EventStruct*, String&)':
**C:/Users/matthijs/Desktop/ESP/ESPEasy-mega/src/_P145_Itho.ino:573:53: error: too many arguments to function 'void addFormSubHeader(const String&)'**

C:/Users/matthijs/Desktop/ESP/ESPEasy-mega/src/WebServer.ino:2713:6: note: declared here
void addFormSubHeader(const String& header)
^
**C:/Users/matthijs/Desktop/ESP/ESPEasy-mega/src/_P145_Itho.ino:575:110: error: invalid conversion from 'char*' to 'int' [-fpermissive]
C:/Users/matthijs/Desktop/ESP/ESPEasy-mega/src/_P145_Itho.ino:575:110: error: too many arguments to function 'void addFormTextBox(const String&, const String&, const String&, int)'**
C:/Users/matthijs/Desktop/ESP/ESPEasy-mega/src/WebServer.ino:2837:6: note: declared here
void addFormTextBox(const String& label, const String& id, const String&  value, int maxlength)
^
**C:/Users/matthijs/Desktop/ESP/ESPEasy-mega/src/_P145_Itho.ino:577:110: error: invalid conversion from 'char*' to 'int' [-fpermissive]**
C:/Users/matthijs/Desktop/ESP/ESPEasy-mega/src/_P145_Itho.ino:577:110: error: too many arguments to function 'void addFormTextBox(const String&, const String&, const String&, int)'
C:/Users/matthijs/Desktop/ESP/ESPEasy-mega/src/WebServer.ino:2837:6: note: declared here
void addFormTextBox(const String& label, const String& id, const String&  value, int maxlength)
^
**C:/Users/matthijs/Desktop/ESP/ESPEasy-mega/src/_P145_Itho.ino:579:110: error: invalid conversion from 'char*' to 'int' [-fpermissive]
C:/Users/matthijs/Desktop/ESP/ESPEasy-mega/src/_P145_Itho.ino:579:110: error: too many arguments to function 'void addFormTextBox(const String&, const String&, const String&, int)'
C:/Users/matthijs/Desktop/ESP/ESPEasy-mega/src/WebServer.ino:2837:6: note: declared here**
void addFormTextBox(const String& label, const String& id, const String&  value, int maxlength)
^
C:/Users/matthijs/Desktop/ESP/ESPEasy-mega/src/_P145_Itho.ino: In function 'void PLUGIN_145_ITHOcheck()':
C:/Users/matthijs/Desktop/ESP/ESPEasy-mega/src/_P145_Itho.ino:647:11: warning: enumeration value 'DucoStandby' not handled in switch [-Wswitch]
C:/Users/matthijs/Desktop/ESP/ESPEasy-mega/src/_P145_Itho.ino:647:11: warning: enumeration value 'DucoLow' not handled in switch [-Wswitch]
C:/Users/matthijs/Desktop/ESP/ESPEasy-mega/src/_P145_Itho.ino:647:11: warning: enumeration value 'DucoMedium' not handled in switch [-Wswitch]
C:/Users/matthijs/Desktop/ESP/ESPEasy-mega/src/_P145_Itho.ino:647:11: warning: enumeration value 'DucoHigh' not handled in switch [-Wswitch]
*** [.pioenvs\normal_ESP8266_1024\src\ESPEasy.ino.cpp.o] Error 1`

**Comment by jvanderzande** [comment]
You need to build it on the v2.0 branch or make some changes to the source for the current mega.
The last 4 warnings are no issue.
I have not tested the supplied bin file, but the source should build fine on v2.0.
Jos

**Comment by matthijsf** [comment]
Thnx, managed to get a build done based on the stable v2.0. Will test multiple ESP's for the hanging interface bug.

**Comment by matthijsf** [comment]
Unfortunately no sigar. On nodemcu it hangs upon enabling the plugin.
Boot without plugin
INIT : Booting version:
INIT : Warm boot #19
FS   : Mounting...
FS   : Mount successful, used 75802 bytes of 957314
INIT : Free RAM:22472
INIT : SPI Init (without CS)
WIFI : AP Mode disabled
WIFI : AP Mode ssid will be ESP_Easy-0 with address 192.168.4.1
WIFI : Connecting Fraaij ESP attempt #0
WD   : Uptime 0 ConnectFailures 0 FreeMem 19904
WIFI : WiFi connect attempt took: 4014 ms
WIFI : Connected! IP: xxx.xxx.xxx.xxx. (ESP_Easy-0) AP: XXXXXXX AP BSSID: XX:XX                          :XX:XX:XX:XX
WD   : Uptime 1 ConnectFailures 0 FreeMem 19648

Plugin Enabled:
INIT : Booting version:
INIT : Warm boot #20
FS   : Mounting...
FS   : Mount successful, used 75802 bytes of 957314
INIT : Free RAM:22472
INIT : SPI Init (without CS)
Extra Settings PLUGIN_145 loaded
CC1101 868Mhz transmitter initialized

**Comment by jvanderzande** [comment]
Maybe a conflict on GPIO ports? What connections do you have?
I have my version running on a WEMOS at this moment and connected exactly in the way the main page describes, but had to disable the I2C Interface settings in the Hardware settings to make the D1 available for the interrupt wire GDO2.
As mentioned, I am running a modified version as I use HTTP to inform Domoticz and didn't want the many updates when T1/T2/T3 options are selected as that send an update each couple of seconds.  
Does it say anything more when you connect it to your computer and monitor the Serial USB log in Atom or your preferred editor?

**Comment by jodur** [comment]
The posted bin is based on V2.0 branch and suitable for devices with 4k flash memory.
For other flash memories you have to compile it your self.
I used a wemos D1 mini, so that should work without problems. Please read the readme.md carefully regarding pins. With the D1 mini you should disable I2C setting as described by @jvanderzande.

**Comment by matthijsf** [comment]
Replaced the CC1101 with the one from a working setup. Boots fine. Issue is not software related but seems to be module related. Also wires need to be as short as possible.

**Comment by glsf91** [comment]
> I'm not sure what esp the bin is built for. However, I've tried to manually build it for a normal_ESP8266_1024 and the build fails with the following errors.
> 
> `C:/Users/matthijs/Desktop/ESP/ESPEasy-mega/src/_P145_Itho.ino:` In function 'boolean Plugin_145(byte, EventStruct*, String&)':
> **C:/Users/matthijs/Desktop/ESP/ESPEasy-mega/src/_P145_Itho.ino:573:53: error: too many arguments to function 'void addFormSubHeader(const String&)'**
> *** [.pioenvs\normal_ESP8266_1024\src\ESPEasy.ino.cpp.o] Error 1`

If you want to make this work on the current development branch of easpeasy you have to change the following lines:

`	  addFormSubHeader(F("Remote RF Controls"));
          addFormTextBox( F("Unit ID remote 1"), F("PLUGIN_145_ID1"), PLUGIN_145_ExtraSettings.ID1, 23);
          addFormTextBox( F("Unit ID remote 2"), F("PLUGIN_145_ID2"), PLUGIN_145_ExtraSettings.ID2, 23);
          addFormTextBox( F("Unit ID remote 3"), F("PLUGIN_145_ID3"), PLUGIN_145_ExtraSettings.ID3, 23);
`
